[package]
name = "laptev-host"
version = "0.1.0"
edition = "2021"
author = "anesthetice"

[dependencies]
lazy_static = "1.4.*"

# networking
tiny_http = "0.12.*"
tokio = { version = "1.27.*", features = ["full"] }

# cryptography
rsa = {version = "0.8.2", features=["pem"]}
aes-gcm-siv = "0.11.1"
rand = "0.8.5"